name: CI

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download IP list
        run: |
          rm -f ip.txt
          {
            wget -qO- https://www.cloudflare-cn.com/ips-v4/#
            echo ""
            wget -qO- https://www.cloudflare.com/ips-v6/#
          } | tee -a ip.txt

      - name: Make script executable and install dependencies
        run: |
          chmod +x CloudflareST
          pip install pandas

      - name: Run TLS scan
        run: |
          ./CloudflareST -httping -cfcolo NYC,SFO,LAX,SEA,SJC,DFW,ORD,HKG -sl 5 -n 20 -url https://speed.cloudflare.com/__down?bytes=66857600
          python convert_csv_to_tls.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.txt
          git commit -m "Update IP list"
          git push
